FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
COPY env.ts ./
COPY drizzle.config.ts ./
COPY src/db ./src/db

CMD ["npx", "drizzle-kit", "studio", "--host", "0.0.0.0", "--port", "4983"]